services:
  # ---------------------------
  # THE GATEWAY (Entry Point)
  # ---------------------------
  kong:
    image: kong:3.4
    container_name: api-gateway
    restart: always
    ports:
      - "8000:8000" # The port you hit from Postman/Frontend
      - "8001:8001" # The Admin API (Optional)
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_LOG_LEVEL: debug
    volumes:
      - ./gateway:/usr/local/kong/declarative # Mount your folder!

  # ---------------------------
  # AUTH SERVICE
  # ---------------------------
  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    environment:
      PORT: 4001
      DATABASE_URL: ${DATABASE_URL}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      NODE_ENV: "development"
    # No ports exposed! Only Kong can talk to it.

  # ---------------------------
  # BUILDING SERVICE
  # ---------------------------
  building-service:
    build: ./services/building-service
    container_name: building-service
    environment:
      PORT: 4002
      DATABASE_URL: "postgresql://postgres:password@postgres:5433/hm-buildings?schema=public"
      NODE_ENV: "development"
    # No ports exposed!
  lease-service:
    build: ./services/lease-service
    container_name: lease-service
    environment:
      PORT: 4003
      DATABASE_URL: "postgresql://postgres:password@postgres:5434/hm-leases?schema=public"
      NODE_ENV: "development"